[package]
name = "iced_mpirs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12", features = ["tokio", "debug", "image", "advanced"] }
#iced_native = "0.12"
iced_runtime = "0.12"
iced_layershell = "0.2.4"
tokio = { version = "1.28", features = ["full"] }
iced_futures = "0.6.0"
env_logger = "0.10.0"
tracing = "0.1.37"

futures-util = "0.3.28"
once_cell = "1.18.0"
serde = { version = "1.0.181", features = ["derive"] }

zbus = { version = "3.14.1", default-features = false, features = ["tokio"] }
tracing-subscriber = "0.3.17"
anyhow = "1.0.72"
