[package]
name = "lala_musicbar"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12", features = ["tokio", "debug", "image", "advanced"] }
#iced_native = "0.12"
iced_runtime = "0.12"
iced_layershell = "0.3.0-beta2"
tokio = { version = "1.39", features = ["full"] }
iced_futures = "0.12.0"
env_logger = "0.11.5"
tracing = "0.1.40"

futures-util = "0.3.30"
once_cell = "1.19.0"
serde = { version = "1.0.204", features = ["derive"] }

zbus = { version = "4.4.0", default-features = false, features = ["tokio"] }
tracing-subscriber = "0.3.18"
anyhow = "1.0.86"
alsa = "0.9.0"
